export enum BottomRoutes {
  Home = "Home",
  DMs = "DMs",
  Mentions = "Mentions",
  Search = "Search",
  You = "You",
}
export enum RootRoutes {
  Verification_Screen = "Verification_Screen",
  SignIn_Screen = "SignIn_Screen",
  Drawer = "Drawer",
  Message = "Message",
  Jump = "Jump",
  Channel_Message = "Channel_Message",
  Add_People = "Add_People",
  NewChannel = "NewChannel",
  Saved = "Saved",
  ChannelInfo = "ChannelInfo",
  MessageThread = "MessageThread",
  AddWorkspace = "AddWorkspace",
  Preferences = "Preferences",
  Sign_Up_Screen = "Sign_Up_Screen",
  EditProfile = "EditProfile",
  Pause_Notification = "Pause_Notification",
  Search_People = "Search_People",
  Create_Workspace = "Create_Workspace",
  User_Profile = "User_Profile",
  Splash_Screen = "Splash_Screen",
  Term_And_Condition = "Term_And_Condition",
  Thread = "Thread",
}
