import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F3F5F5",
  },
  logo_Style: {
    marginTop: 80,
    marginLeft: 35,
  },
  Sign_In_To_ConfigueeX_Text_Style: {
    fontSize: 14,
    ////fontFamily: "PlusJakartaSans-Bold",
    lineHeight: 18,
    textAlign: "center",
    width: "80%",
    marginBottom: 30,
  },
  textStyle: {
    fontSize: 14,
    color: "#000000",
    backgroundColor: "white",
    height: 50,
    width: "80%",
    borderRadius: 5,
    //fontFamily: "PlusJakartaSans-Regular",
    paddingLeft: 10,
  },
  forgottextStyle: {
    fontSize: 15,
    marginHorizontal: "11%",
    marginTop: "4%",
    color: "#656971",
    textAlign: "justify",
    alignSelf: "flex-end",
  },
  signUpButton: {
    width: "87%",
    backgroundColor: "#3866E6",
    marginTop: 22,
    alignItems: "center",
    borderRadius: 5,
    height: 50,
    justifyContent: "center",
  },
  testSignUp: {
    color: "#ffffff",
    fontSize: 14,
    ////fontFamily: "PlusJakartaSans-Bold",
  },
  containerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  bottom_Style: {
    alignItems: "center",
    flex: 1.5,
  },
  need_Configure_X_Text_Style: {
    //fontFamily: "PlusJakartaSans-Medium",
    color: "#656971",
    fontSize: 12,
    textAlign: "center",
    marginTop: 17,
    width: "80%",
  },
  checkBoxStyle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginTop: 20,
    width: "85%",
  },
  createAccountStyle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 5,
    width: "80%",
    marginBottom: 35,
  },
  createAccount_Text_Style: {
    color: "#3866E6",
    fontSize: 12,
    textAlign: "center",
    ////fontFamily: "PlusJakartaSans-Bold",
    marginRight: 3,
  },
  shadowProp: {
    color: "#FFFFFF",
    backgroundColor: "white",
    width: "87%",
    borderWidth: 2,
    borderColor: "#FFFFFF",
    borderRadius: 8,
    shadowColor: "#B0B9C3",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.4,
    shadowRadius: 1,
    marginTop: 20,
  },
  Text_Style: {
    //fontFamily: "PlusJakartaSans-Medium",
    color: "#656971",
    fontSize: 12,
    textAlign: "center",
    paddingLeft: 8,
    paddingRight: 3,
  },
});
