import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F3F5F5",
  },
  logo_Style: {
    bottom: "2%",
    marginLeft: 35,
  },
  Sign_In_To_ConfigueeX_Text_Style: {
    fontSize: 14,
    ////fontFamily: "PlusJakartaSans-Bold",
    lineHeight: 18,
    textAlign: "center",
    width: "80%",
  },
  textStyle: {
    fontSize: 15,
    color: "#000000",
    backgroundColor: "white",
    height: 52,
    width: "80%",
    borderWidth: 2,
    borderColor: "#FFFFFF",
    borderRadius: 8,
    //fontFamily: "PlusJakartaSans-Regular",
    paddingLeft: 10,
  },
  forgottextStyle: {
    fontSize: 15,
    marginHorizontal: "11%",
    marginTop: "4%",
    color: "#656971",
    textAlign: "justify",
    alignSelf: "flex-end",
  },
  signUpButton: {
    width: "80%",
    backgroundColor: "#3866E6",
    marginTop: 22,
    alignItems: "center",
    borderRadius: 8,
    // borderWidth: 2,
    height: 56,
    justifyContent: "center",
  },
  testSignUp: {
    color: "#ffffff",
    fontSize: 14,
    ////fontFamily: "PlusJakartaSans-Bold",
  },
  // buttonDark: {
  //   alignItems: "center",
  //   justifyContent: "center",
  //   flexDirection: "row",
  //   height: 89,
  //   width: 320,
  //   borderRadius: 10,
  //   borderColor: "#EAEAEA",
  //   backgroundColor: "#fff",
  //   shadowColor: "rgba(0, 0, 0, 0.01)",
  //   shadowOffset: {
  //     width: 0,
  //     height: 0,
  //   },
  //   paddingVertical: 20,
  //   paddingHorizontal: 23,
  //   shadowRadius: 4,
  //   elevation: 5,
  // },
  // buttonWhite: {
  //   marginTop: "5%",
  //   backgroundColor: "white",
  //   width: 300,
  //   height: 52,
  //   justifyContent: "center",
  //   alignItems: "center",
  //   borderWidth: 1.3,
  //   borderRadius: 8,
  //   shadowColor: "#000",
  //   shadowOffset: {
  //     width: 0,
  //     height: 2,
  //   },
  //   shadowOpacity: 0.25,
  //   shadowRadius: 3.84,
  //   elevation: 5,
  // },
  // buttonWhiteText: {
  //   fontSize: 16,
  //   color: "#202020",
  //   textAlign: "center",
  //   fontWeight: "500",
  //   lineHeight: 19.36,
  // },
  containerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  bottom_Style: {
    alignItems: "center",
    flex: 1,
  },
  need_Configure_X_Text_Style: {
    //fontFamily: "PlusJakartaSans-Medium",
    color: "#656971",
    fontSize: 12,
    textAlign: "center",
    marginTop: 17,
    width: "80%",
  },
  createAccountStyle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 5,
    width: "80%",
  },
  createAccount_Text_Style: {
    color: "#3866E6",
    fontSize: 12,
    textAlign: "center",
    ////fontFamily: "PlusJakartaSans-Bold",
    marginRight: 3,
  },
  shadowProp: {
    color: "#FFFFFF",
    backgroundColor: "white",
    width: "80%",
    borderWidth: 2,
    borderColor: "#FFFFFF",
    borderRadius: 8,
    shadowColor: "#B0B9C3",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.4,
    shadowRadius: 1,
    marginTop: 29,
  },
});
